[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions/"
  timeout = 25
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
