# netlify.toml — propre et minimal pour Vite/React
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Redirection SPA (React Router, etc.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
