# Fichier: netlify.toml (Version finale et correcte)

[build]
  command = "npm run build"
  publish = "dist"

# Configuration pour les fonctions Serverless
[functions]
  # Indique à Netlify où trouver les fonctions
  directory = "netlify/functions/"
  # Augmente le temps d'exécution max à 25 secondes
  timeout = 25
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
