# Fichier: netlify.toml (Version corrigée et complète)

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
    directory = "netlify/functions"

# Redirection pour les Single Page Applications (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
